# Generated by Django 5.1.1 on 2025-11-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='is_encrypted',
            new_name='encrypted',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='sha256',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=200),
        ),
    ]
