# Generated by Django 5.1.1 on 2025-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_is_encrypted_uploadedfile_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='encrypted',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
